/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   GPIO Example
  ******************************************************************************
*/

#include "stm32f1xx.h"
#include "stdint.h"

void delayMs(uint16_t time) {
	/* Configure SysTick */
	SysTick->LOAD = 8000-1;		/* 1ms @8MHz */
	SysTick->VAL = 0;			/* Clear current value register */
	SysTick->CTRL = 5;			/* Enable SysTick */

	for(uint16_t i = 0; i < time; i++) {
		/* Wait until the COUNT flag is set */
		while(((SysTick->CTRL & SysTick_CTRL_COUNTFLAG_Msk) >> 16) == 0);
	}

	SysTick->CTRL = 0;
}


int main(void)
{
  /* Enable GPIOC clocks. */
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
	/* Set PC13 as push-pull output */
	GPIOC->CRH |= GPIO_CRH_MODE13_0;
	GPIOC->CRH &= ~GPIO_CRH_MODE13_1;
	GPIOC->CRH &= ~GPIO_CRH_CNF13_1;
	GPIOC->CRH &= ~GPIO_CRH_CNF13_0;

	while(1) {
		if(GPIOC->IDR & GPIO_IDR_IDR_14) {
			// Turn off PC13
			GPIOC->BSRR |= GPIO_BSRR_BR13;
		} else {
			// Turn on PC13
			GPIOC->BSRR |= GPIO_BSRR_BS13;
			delayMs(200);
			// Turn off PC13
			GPIOC->BSRR |= GPIO_BSRR_BR13;
			delayMs(200);
		}
	}
}
