/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "stm32f4xx.h"
#include "stdint.h"

void delayMs(uint32_t delay) {
	for(; delay > 0; delay--)
		for(uint32_t i = 0; i < 3195; i++);
}

int main(void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	// Set PB15 as output
	GPIOA->MODER |= GPIO_MODER_MODER5_0;
	// Set PC13 as input
	GPIOC->MODER &= ~(GPIO_MODER_MODER13);

	while(1) {
		if(GPIOC->IDR & GPIO_IDR_IDR_13) {
			// Turn off PA5
			GPIOA->BSRRH |= GPIO_BSRR_BS_5;
		} else {
			// Turn on PA5
			//GPIOA->ODR |= GPIO_ODR_ODR_5;
			GPIOA->BSRRL |= GPIO_BSRR_BS_5;
			delayMs(200);
			// Turn off PA5
			//GPIOA->ODR &= ~(GPIO_ODR_ODR_5);
			GPIOA->BSRRH |= GPIO_BSRR_BS_5;
			delayMs(200);
		}
	}
}
